In [ ]:
import numpy as np
a = np.array([1,3,4,1,0,3,8,0])
np.info(np.add)


In [3]:
print(a.any(0))

True


In [9]:
print(np.isfinite(a))
a = np.array([1,2,np.nan,np.inf])
print(np.isfinite(a))


[ True  True  True  True  True  True  True  True]
[ True  True False False]


In [10]:
print(np.isnan(a))

[False False  True False]


In [20]:
b = np.zeros(10,dtype = 'int')
print(b)
c = np.ones(10,dtype = 'int')
print(c)
d = c.copy()
d *= 5
print(d)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


In [26]:
d = np.arange(30,71)
print(d)
e = np.arange(30,71,2)
print(e)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [32]:
f = np.identity(3,dtype = 'int')
print(f)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [44]:
r = np.random.random()
r

0.33392535297367987

In [63]:
arr = np.arange(np.random.random(),15)
arr

array([ 0.53483779,  1.53483779,  2.53483779,  3.53483779,  4.53483779,
        5.53483779,  6.53483779,  7.53483779,  8.53483779,  9.53483779,
       10.53483779, 11.53483779, 12.53483779, 13.53483779, 14.53483779])

In [67]:
vec = np.arange(15,55)
print(vec)
print(vec[1:54])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [ ]:
vec = np.arange(12).reshape(3,4)
for i in vec:
    print(i)

In [72]:
import numpy as np
x = np.random.randint(0, 11, 5)
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
print(x)


Vector of length 5 filled with arbitrary integers from 0 to 10:
[6 9 1 6 3]


In [80]:
first = np.array([1,2,3,4,5])
second = np.array([6,7,8,9,9])
res = first * second
print(res)

[ 6 14 24 36 45]


In [87]:
mat = np.eye(3,dtype = 'int')
print(mat)
print(mat.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
(3, 3)


In [93]:
mat = np.ones((10,10),dtype = 'int')
mat[1:9,1:9] = 0
print(mat)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [97]:
x = np.zeros((4, 4),dtype = 'int')
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)


[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [98]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])
print("Original vector:")
print(v)
print("Original matrix:")
print(m)
result = np.empty_like(m) 
for i in range(4):
  result[i, :] = m[i, :] + v
print("\nAfter adding the vector v to each row of the matrix m:")
print(result)


Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After adding the vector v to each row of the matrix m:
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]
