In [9]:
import numpy as np
x = np.array([340,1080,640,880,490,510])
y = np.array([500,1700,1110,800,1400,500])
a = x - 656.67
print(a)
b = y - 1001.67
print(b)
print(a * b)
print(a ** 2)
print((a * b).sum())
print((a ** 2).sum())

print((a * b).sum() / (a ** 2).sum())
print(1001.)

[-316.67  423.33  -16.67  223.33 -166.67 -146.67]
[-501.67  698.33  108.33 -201.67  398.33 -501.67]
[158863.8389 295624.0389  -1805.8611 -45038.9611 -66389.6611  73579.9389]
[100279.8889 179208.2889    277.8889  49876.2889  27778.8889  21512.0889]
414833.3334
378933.3334
1.0947396199692576
